app = "kali-desktop"
primary_region = "iad"

[build]

[env]
  DISPLAY = ":0"

[http_service]
  internal_port = 6080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services.http_checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "30s"
  method = "GET"
  path = "/"

[[services]]
  internal_port = 3389
  protocol = "tcp"

  [[services.ports]]
    port = 3389

[mounts]
  source = "kali_data"
  destination = "/root"
  initial_size = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 8
  memory_mb = 16384
