# fly.toml app configuration file generated for lj-vdoo on 2025-11-29T11:58:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lj-vdoo'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 6080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 16384
